### PR TITLE
AppContext and tweaks

### PR DESCRIPTION
**Pull request by dizzyup**
- Creates an AppContext so we can get state globally instead of passing props everywhere
- Creates a standard `Fallback` component which contains loading and error states
- Hides the Docs link for now
- Fixes remaining console warnings/errors
- When writing the current order to localStorage, the associated payment is now stored as a `payment` object on the order

### CODE REVIEW

**Comment by dizzyup** [comment]
@im2nguyen I've got one remaining issue which I'm not sure how to resolve - the SWR orders object doesn't get updated when other changes happen. 

Best example of this is when placing a new order, as soon as you hit the order confirmation page, open the account panel and you'll see the current order isn't in the history, and won't appear until a full refresh.

It's also noticeable when signing out. If you sign out and then sign in with different creds, the order history will show the orders for the previous user, again until a full refresh.

Any ideas how we could handle this?

**Comment by im2nguyen** [comment]
Hey @dizzyup, I just pushed a commit that _should_ resolve the issue you pointed out.

The problem was that the Apollo client kept trying to retrieve the items from cache since they existed. If you log the `data` from the `Orders.js` component, it returns a networkStatus of [7](https://github.com/apollographql/apollo-client/blob/d96f4578f89b933c281bb775a39503f6cdb59ee8/src/core/networkStatus.ts#L4) (no request sent for query).

To address this, for orders, I refetched `Orders` after payments and I cleared apollo's cache when a user logs out. It's working locally, can you test it on yours?

**Comment by dizzyup** [comment]
Perfect! That's everything working as expected now. I'm going to do an hour or so of work to improve the way we display some errors, otherwise I think this is good to go!

**Comment by dizzyup** [comment]
@im2nguyen All set!

**Pull request merged**
